// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxotwwohzvqaignpzmic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4b3R3d29oenZxYWlnbnB6bWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzcyMDIsImV4cCI6MjA3MDMxMzIwMn0.ROHrusMX1-BtzwkbEH5mbJpwZUCloA8WmDnvjP03MWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});